sudo: false
language: node_js
node_js:
  - iojs
  - '0.12'
  - '0.10'

notifications:
  email:
    recipients:
      - diegorodrigues92@gmail.com
    on_success: always

matrix:
  allow_failures:
    - node_js: iojs
